# Generated by Django 5.0.3 on 2024-04-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name_plural': 'checkouts'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'devices'},
        ),
    ]
